// This file was generated by executing this statement: wav2c sounds_notebank/A.wav
extern uint16_t A_wav[];
#define A_WAV_SAMPLE_RATE 441000
#define A_WAV_BITS_PER_SAMPLE 16
#define A_WAV_NUMBER_OF_SAMPLES 176420
