// This file was generated by executing this statement: wav2c C4_E4_C5_sine.wav
extern uint16_t C4_E4_C5_sine_wav[];
#define C4_E4_C5_SINE_WAVQ_SAMPLE_RATE 441000
#define C4_E4_C5_SINE_WAVQ_BITS_PER_SAMPLE 16
#define C4_E4_C5_SINE_WAVQ_NUMBER_OF_SAMPLES 352800
