// This file was generated by executing this statement: wav2c C4_sine.wav
extern uint16_t C4_sine_wav[];
#define C4_SINE_WAV_SAMPLE_RATE 441000
#define C4_SINE_WAV_BITS_PER_SAMPLE 16
#define C4_SINE_WAV_NUMBER_OF_SAMPLES 352800
