// This file was generated by executing this statement: wav2c C5_F5_sine.wav
extern uint16_t C5_F5_sine_wav[];
#define C5_F5_SINE_WAV_SAMPLE_RATE 441000
#define C5_F5_SINE_WAV_BITS_PER_SAMPLE 16
#define C5_F5_SINE_WAV_NUMBER_OF_SAMPLES 44100
