// This file was generated by executing this statement: wav2c C5_sine.wav
extern uint16_t C5_sine_wav[];
#define C5_SINE_WAVE_SAMPLE_RATE 441000
#define C5_SINE_WAVE_BITS_PER_SAMPLE 16
#define C5_SINE_WAVE_NUMBER_OF_SAMPLES 352800
