// This file was generated by executing this statement: wav2c C_New.wav
extern uint16_t C_New_wav[];
#define C_NEW_WAV_SAMPLE_RATE 441000
#define C_NEW_WAV_BITS_PER_SAMPLE 16
#define C_NEW_WAV_NUMBER_OF_SAMPLES 176420
