// This file was generated by executing this statement: wav2c D5_G5_sine.wav
extern uint16_t D5_G5_sine_wav[];
#define D5_G5_SINE_WAV_SAMPLE_RATE 441000
#define D5_G5_SINE_WAV_BITS_PER_SAMPLE 16
#define D5_G5_SINE_WAV_NUMBER_OF_SAMPLES 44100
