// This file was generated by executing this statement: wav2c E4_sine.wav
extern uint16_t E4_sine_wav[];
#define E4_SINE_WAV_SAMPLE_RATE 441000
#define E4_SINE_WAV_BITS_PER_SAMPLE 16
#define E4_SINE_WAV_NUMBER_OF_SAMPLES 352800
