// This file was generated by executing this statement: wav2c F4_A4_sine.wav
extern uint16_t F4_A4_sine_wav[];
#define F4_A4_SINE_WAV_SAMPLE_RATE 441000
#define F4_A4_SINE_WAV_BITS_PER_SAMPLE 16
#define F4_A4_SINE_WAV_NUMBER_OF_SAMPLES 44100
