// This file was generated by executing this statement: wav2c F5_sine.wav
extern uint16_t F5_sine_wav[];
#define F5_SINE_WAV_SAMPLE_RATE 441000
#define F5_SINE_WAV_BITS_PER_SAMPLE 16
#define F5_SINE_WAV_NUMBER_OF_SAMPLES 44100
