// This file was generated by executing this statement: wav2c G4_G5_sine.wav
extern uint16_t G4_G5_sine_wav[];
#define G4_G5_SINE_WAV_SAMPLE_RATE 441000
#define G4_G5_SINE_WAV_BITS_PER_SAMPLE 16
#define G4_G5_SINE_WAV_NUMBER_OF_SAMPLES 44100
