// This file was generated by executing this statement: wav2c G4_sine.wav
extern uint16_t G4_sine_wav[];
#define G4_SINE_WAVø_SAMPLE_RATE 441000
#define G4_SINE_WAVø_BITS_PER_SAMPLE 16
#define G4_SINE_WAVø_NUMBER_OF_SAMPLES 352800
